import { bindNumberAndSlider } from "../bind.js";
import { createElement } from "../domHelpers.js";
import { tipIcon } from "../tooltip.js";

export function sliderField(id, label, unit, hint, min, max, step, tip) {
  const u = unit ? ` <span class="unit">${unit}</span>` : "";
  return `<div class="form-row"><div><div class="label">${label}${u} ${tipIcon(tip || "")}</div><div class="hint">${hint || ""}</div></div><div class="input-pair"><input id="${id}" type="number" min="${min}" max="${max}" step="${step}" aria-label="${label}" /><input id="${id}_slider" type="range" min="${min}" max="${max}" step="${step}" aria-label="${label} slider" /><div class="range-meta"><span id="${id}_min"></span><span id="${id}_max"></span></div></div></div>`;
}

export function createContextSummaryCard(label, value, meta = "") {
  return createElement("div", { className: "context-summary__card" }, [
    createElement("div", { className: "context-summary__label", text: label }),
    createElement("div", { className: "context-summary__value", text: value }),
    meta ? createElement("div", { className: "context-summary__meta", text: meta }) : null,
  ]);
}

export function bindPair(root, id, min, max, step) {
  const n = root.querySelector(`#${id}`);
  const s = root.querySelector(`#${id}_slider`);
  const mn = root.querySelector(`#${id}_min`);
  const mx = root.querySelector(`#${id}_max`);
  if (!n || !s || !mn || !mx) return null;
  mn.textContent = String(min);
  mx.textContent = String(max);
  return bindNumberAndSlider({ numberEl: n, sliderEl: s, min, max, step, mode: "linear" });
}

export function collectCalendarPageElements(wrap) {
  const $ = (sel) => wrap.querySelector(sel);
  return {
    profileSummaryCopy: $("#calProfileSummaryCopy"),
    profileSummaryGrid: $("#calProfileSummaryGrid"),
    profileSummaryNotes: $("#calProfileSummaryNotes"),
    rulesSummary: $("#calRulesSummary"),
    drawerToggle: $("#calDrawerToggle"),
    profileSelect: $("#calProfileSelect"),
    profileNew: $("#calProfileNew"),
    profileDuplicate: $("#calProfileDuplicate"),
    profileDelete: $("#calProfileDelete"),
    sourcePlanet: $("#calSourcePlanet"),
    primaryMoon: $("#calPrimaryMoon"),
    extraMoon1: $("#calExtraMoon1"),
    extraMoon2: $("#calExtraMoon2"),
    extraMoon3: $("#calExtraMoon3"),
    derivedData: $("#calDerivedData"),
    derivedRoundEnabled: $("#calDerivedRoundEnabled"),
    derivedDecimalPlaces: $("#calDerivedDecimalPlaces"),
    monthsPerYear: $("#calMonthsPerYear"),
    daysPerMonth: $("#calDaysPerMonth"),
    daysPerWeek: $("#calDaysPerWeek"),
    structureInfo: $("#calStructureInfo"),
    useSelected: $("#calUseSelected"),
    calendarName: $("#calCalendarName"),
    basis: $("#calBasis"),
    year: $("#calYear"),
    month: $("#calMonth"),
    startDay: $("#calStartDay"),
    weekStart: $("#calWeekStart"),
    moonEpoch: $("#calMoonEpoch"),
    yearDisplayMode: $("#calYearDisplayMode"),
    yearOffset: $("#calYearOffset"),
    yearPrefix: $("#calYearPrefix"),
    yearSuffix: $("#calYearSuffix"),
    preCalendarStartYear: $("#calPreCalendarStartYear"),
    postEraLabel: $("#calPostEraLabel"),
    preEraLabel: $("#calPreEraLabel"),
    preCalendarUseYearZero: $("#calPreCalendarUseYearZero"),
    dayNames: $("#calDayNames"),
    weekNames: $("#calWeekNames"),
    monthNames: $("#calMonthNames"),
    monthLengthOverridesEnabled: $("#calMonthLengthOverridesEnabled"),
    monthLengthOverridesRow: $("#calMonthLengthOverridesRow"),
    monthLengthOverrides: $("#calMonthLengthOverrides"),
    eraName: $("#calEraName"),
    eraStartYear: $("#calEraStartYear"),
    eraAdd: $("#calEraAdd"),
    eraList: $("#calEraList"),
    jsonText: $("#calJsonText"),
    jsonStatus: $("#calJsonStatus"),
    exportDownload: $("#calExportDownload"),
    exportCopy: $("#calExportCopy"),
    importFileBtn: $("#calImportFileBtn"),
    importFile: $("#calImportFile"),
    importApply: $("#calImportApply"),
    jsonLoadCurrent: $("#calJsonLoadCurrent"),
    markerEnabled: $("#calMarkerEnabled"),
    markerSeasons: $("#calMarkerSeasons"),
    markerSeasonBands: $("#calMarkerSeasonBands"),
    markerEclipses: $("#calMarkerEclipses"),
    pdfMonth: $("#calPdfMonth"),
    pdfYear: $("#calPdfYear"),
    icsAnchor: $("#calIcsAnchor"),
    icsIncHolidays: $("#calIcsIncHolidays"),
    icsIncFestivals: $("#calIcsIncFestivals"),
    icsIncMarkers: $("#calIcsIncMarkers"),
    icsMonth: $("#calIcsMonth"),
    icsYear: $("#calIcsYear"),
    outputStatus: $("#calOutputStatus"),
    resetNames: $("#calResetNames"),
    holidayName: $("#calHolidayName"),
    holidayCategory: $("#calHolidayCategory"),
    holidayColorTag: $("#calHolidayColorTag"),
    holidayRecurrence: $("#calHolidayRecurrence"),
    holidayCycleYears: $("#calHolidayCycleYears"),
    holidayOffsetYear: $("#calHolidayOffsetYear"),
    holidayAdvancedToggle: $("#calHolidayAdvancedToggle"),
    holidayIssueStatus: $("#calHolidayIssueStatus"),
    holidayYear: $("#calHolidayYear"),
    holidayUseDate: $("#calHolidayUseDate"),
    holidayUseWeekday: $("#calHolidayUseWeekday"),
    holidayUseMoon: $("#calHolidayUseMoon"),
    holidayUseRelative: $("#calHolidayUseRelative"),
    holidayRelativeType: $("#calHolidayRelativeType"),
    holidayRelativeOffset: $("#calHolidayRelativeOffset"),
    holidayRelativeMoonSlot: $("#calHolidayRelativeMoonSlot"),
    holidayRelativeMoonPhase: $("#calHolidayRelativeMoonPhase"),
    holidayRelativeMarker: $("#calHolidayRelativeMarker"),
    holidayRelativeHoliday: $("#calHolidayRelativeHoliday"),
    holidayAnchorType: $("#calHolidayAnchorType"),
    holidayAlgorithm: $("#calHolidayAlgorithm"),
    holidayAlgorithmSupportHint: $("#calHolidayAlgorithmSupportHint"),
    holidayAnchorMoonSlot: $("#calHolidayAnchorMoonSlot"),
    holidayAnchorMoonPhase: $("#calHolidayAnchorMoonPhase"),
    holidayAnchorMarker: $("#calHolidayAnchorMarker"),
    holidayAnchorHoliday: $("#calHolidayAnchorHoliday"),
    holidayAnchorOffset: $("#calHolidayAnchorOffset"),
    holidayConflictRule: $("#calHolidayConflictRule"),
    holidayMaxShiftDays: $("#calHolidayMaxShiftDays"),
    holidayStayInMonth: $("#calHolidayStayInMonth"),
    holidayConflictScope: $("#calHolidayConflictScope"),
    holidayConflictCategories: $("#calHolidayConflictCategories"),
    holidayConflictHolidayIds: $("#calHolidayConflictHolidayIds"),
    holidayStartMonth: $("#calHolidayStartMonth"),
    holidayDayOfMonth: $("#calHolidayDayOfMonth"),
    holidayDuration: $("#calHolidayDuration"),
    holidayPriority: $("#calHolidayPriority"),
    holidayMergeMode: $("#calHolidayMergeMode"),
    holidayWeekday: $("#calHolidayWeekday"),
    holidayOccurrence: $("#calHolidayOccurrence"),
    holidayMoonSlot: $("#calHolidayMoonSlot"),
    holidayMoonPhase: $("#calHolidayMoonPhase"),
    holidayExceptYears: $("#calHolidayExceptYears"),
    holidayExceptMonths: $("#calHolidayExceptMonths"),
    holidayExceptDays: $("#calHolidayExceptDays"),
    holidaySave: $("#calHolidaySave"),
    holidayCancel: $("#calHolidayCancel"),
    holidayList: $("#calHolidayList"),
    festivalName: $("#calFestivalName"),
    festivalCategory: $("#calFestivalCategory"),
    festivalColorTag: $("#calFestivalColorTag"),
    festivalRecurrence: $("#calFestivalRecurrence"),
    festivalCycleYears: $("#calFestivalCycleYears"),
    festivalOffsetYear: $("#calFestivalOffsetYear"),
    festivalYear: $("#calFestivalYear"),
    festivalStartMonth: $("#calFestivalStartMonth"),
    festivalAfterDay: $("#calFestivalAfterDay"),
    festivalDuration: $("#calFestivalDuration"),
    festivalOutsideWeek: $("#calFestivalOutsideWeek"),
    festivalExceptYears: $("#calFestivalExceptYears"),
    festivalExceptMonths: $("#calFestivalExceptMonths"),
    festivalExceptDays: $("#calFestivalExceptDays"),
    festivalSave: $("#calFestivalSave"),
    festivalCancel: $("#calFestivalCancel"),
    festivalList: $("#calFestivalList"),
    intercalaryName: $("#calIntercalaryName"),
    intercalaryPlacement: $("#calIntercalaryPlacement"),
    intercalaryAnchorMonth: $("#calIntercalaryAnchorMonth"),
    intercalaryRecurrence: $("#calIntercalaryRecurrence"),
    intercalaryYear: $("#calIntercalaryYear"),
    intercalaryCycleYears: $("#calIntercalaryCycleYears"),
    intercalaryOffsetYear: $("#calIntercalaryOffsetYear"),
    intercalaryDurationMode: $("#calIntercalaryDurationMode"),
    intercalaryDuration: $("#calIntercalaryDuration"),
    intercalaryWeekdayFlow: $("#calIntercalaryWeekdayFlow"),
    intercalaryExceptYears: $("#calIntercalaryExceptYears"),
    intercalarySave: $("#calIntercalarySave"),
    intercalaryCancel: $("#calIntercalaryCancel"),
    intercalaryList: $("#calIntercalaryList"),
    leapName: $("#calLeapName"),
    leapCycle: $("#calLeapCycle"),
    leapOffset: $("#calLeapOffset"),
    leapMonth: $("#calLeapMonth"),
    leapDelta: $("#calLeapDelta"),
    leapAdd: $("#calLeapAdd"),
    leapSuggest: $("#calLeapSuggest"),
    leapStatus: $("#calLeapStatus"),
    leapList: $("#calLeapList"),
    cycleName: $("#calCycleName"),
    cycleMode: $("#calCycleMode"),
    cycleWeekendRule: $("#calCycleWeekendRule"),
    weekendDays: $("#calWeekendDays"),
    cycleStartDay: $("#calCycleStartDay"),
    cycleOnDays: $("#calCycleOnDays"),
    cycleOffDays: $("#calCycleOffDays"),
    cycleIntervalDays: $("#calCycleIntervalDays"),
    cycleActiveLabel: $("#calCycleActiveLabel"),
    cycleRestLabel: $("#calCycleRestLabel"),
    cycleMarkerLabel: $("#calCycleMarkerLabel"),
    cycleActiveShort: $("#calCycleActiveShort"),
    cycleRestShort: $("#calCycleRestShort"),
    cycleMarkerShort: $("#calCycleMarkerShort"),
    cycleSave: $("#calCycleSave"),
    cycleCancel: $("#calCycleCancel"),
    cycleList: $("#calCycleList"),
    prevMonth: $("#calPrevMonth"),
    nextMonth: $("#calNextMonth"),
    openDetail: $("#calOpenDetail"),
    monthTitle: $("#calMonthTitle"),
    chipRow: $("#calChipRow"),
    seasonBand: $("#calSeasonBand"),
    intercalaryBefore: $("#calIntercalaryBefore"),
    intercalaryAfter: $("#calIntercalaryAfter"),
    moonLegend: $("#calMoonLegend"),
    selectedDay: $("#calSelectedDay"),
    compactGrid: $("#calCompactGrid"),
    compactEvents: $("#calCompactEvents"),
    auditPanel: $("#calAuditPanel"),
    auditScope: $("#calAuditScope"),
    auditKind: $("#calAuditKind"),
    auditPreview: $("#calAuditPreview"),
    auditAgenda: $("#calAuditAgenda"),
    holidayFilters: $("#calHolidayFilters"),
    miniHead: $("#calMiniHead"),
    miniBody: $("#calMiniBody"),
    jumpAbs: $("#calJumpAbs"),
    jumpAbsBtn: $("#calJumpAbsBtn"),
    jumpYear: $("#calJumpYear"),
    jumpMonth: $("#calJumpMonth"),
    jumpDay: $("#calJumpDay"),
    jumpDateBtn: $("#calJumpDateBtn"),
    jumpResolved: $("#calJumpResolved"),
    detailOverlay: $("#calDetailOverlay"),
    detailPrev: $("#calDetailPrev"),
    detailNext: $("#calDetailNext"),
    closeDetail: $("#calCloseDetail"),
    detailMonthTitle: $("#calDetailMonthTitle"),
    detailChipRow: $("#calDetailChipRow"),
    detailSeasonBand: $("#calDetailSeasonBand"),
    detailMoonLegend: $("#calDetailMoonLegend"),
    detailIntercalaryBefore: $("#calDetailIntercalaryBefore"),
    detailSelectedDay: $("#calDetailSelectedDay"),
    detailHead: $("#calDetailHead"),
    detailBody: $("#calDetailBody"),
    detailIntercalaryAfter: $("#calDetailIntercalaryAfter"),
  };
}
